apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3fs-test-pvc-static-path
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce # Or ReadOnlyMany for scaleout
  resources:
    requests:
      storage: 5Gi
  storageClassName: s3fs-csi-static-path
