---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: s3fs-csi-static-path
provisioner: ch.ctrox.csi.s3-driver
# reclaimPolicy: Retain
parameters:
  # specify which mounter to use
  # can be set to rclone, s3fs, goofys or s3backer
  mounter: rclone
  # to use an existing bucket, specify it here:
  bucket: bucket-1
  usePrefix: "true"
  prefix: test
  csi.storage.k8s.io/provisioner-secret-name: s3fs-csi-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/controller-publish-secret-name: s3fs-csi-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: s3fs-csi-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
  csi.storage.k8s.io/node-publish-secret-name: s3fs-csi-secret
  csi.storage.k8s.io/node-publish-secret-namespace: default
